name: 'Auto Pr labelr'
description: 'Automatically label new Pull requests'
author: 'Uchenna Okoro'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  label:
    description: 'Label to add to new Pull requests'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'bookmark'
  color: 'green'
