name: 'Pr labelr'
description: 'Automatically label new Pull requests'
author: 'Uchenna Sylvester Okoro'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  default-label:
    description: 'A default label to add to PRs'
    required: false
    default: 'pending-review'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'bookmark'
  color: 'green'
