name: 'Auto Label PRs'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add label to PR
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'
